### PR TITLE
Small improvements

### PR DESCRIPTION
**Pull request by djoos**
Hi there,

I've made some small improvements to the cookbook:
1) build-essential needs to be installed
2) I've taken out the to do, as it's not necessary: PHP will pick it up in conf.d
3) improvement on the extension_dir strip

Do let me know if you have any question or remarks and thanks in advance for merging this PR!

Kind regards,
David

### CODE REVIEW

**Comment by djoos** [comment]
_kick_

**Comment by dkingofpa** [comment]
Sorry.  We haven't touched or used this repo in 2 years.  You'd be better served by finding another xdebug chef cookbook.

**Comment by djoos** [comment]
Hi @dkingofpa,

thanks for getting in touch!

we maintain a whole host of related cookbooks (phpunit, phpcs, pdepend, etc. please do have a look at https://github.com/escapestudios-cookbooks) - would you potentially be interested in transferring the xdebug cookbook over so we can maintain it going forward as well as publish it as a Chef community cookbook?

Thanks in advance!

Kind regards,
David

**Comment by djoos** [comment]
_kick_

**Comment by dkingofpa** [comment]
Transferring repo ownership to Escape Studios.

**Comment by djoos** [comment]
Thanks @dkingofpa!

**Pull request merged**
